const YEARS=Array.from({length:12},(_,i)=>{const y=2024+i;return{year:y,label:`${y}-${y+1}`,field:`mat_${y}_${y+1}`}});
const map=L.map('map').setView([19.36,-99.13],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);
let agebData,alcaldiaData,schools=[],conapo=[],analysis=[],layer,currentIndex=0,currentTerritory='ageb',currentVariable='total',currentFilter='all',rankMode='decline';
const $=id=>document.getElementById(id),n=v=>Number(v)||0,pct=(cur,base)=>base?((cur-base)/base)*100:null,fmt=v=>n(v).toLocaleString('es-MX');
YEARS.forEach((y,i)=>$('yearSelect').insertAdjacentHTML('beforeend',`<option value="${i}">${y.label}</option>`));
function currentValue(f){const p=f.properties,cur=n(p[YEARS[currentIndex].field]);return currentVariable==='total'?cur:pct(cur,n(p.mat_2024_2025))}
function visible(f){if(currentTerritory!=='ageb')return true;const k=n(f.properties.num_escuelas);return currentFilter==='with'?k>0:currentFilter==='without'?k===0:true}
function quantiles(vals){const a=vals.filter(v=>v!=null&&v>0).sort((x,y)=>x-y);if(!a.length)return[1,2,3,4];const q=p=>a[Math.floor((a.length-1)*p)];return[q(.2),q(.4),q(.6),q(.8)]}
function totalColor(v,b){if(v<=0)return'#e5e7eb';if(v<=b[0])return'#eff3ff';if(v<=b[1])return'#bdd7e7';if(v<=b[2])return'#6baed6';if(v<=b[3])return'#3182bd';return'#08519c'}
function pctColor(v){if(v==null)return'#d1d5db';if(v<-10)return'#7f0000';if(v<-7)return'#b2182b';if(v<-4)return'#d6604d';if(v<-2)return'#f4a582';if(v<=2)return'#f7f7f7';if(v<=5)return'#d9f0d3';if(v<=10)return'#7fbf7b';if(v<=20)return'#1b7837';return'#00441b'}
function enrichAlcaldias(){const agg={};agebData.features.forEach(f=>{const m=String(f.properties.CVE_MUN||'').padStart(3,'0');if(!agg[m])agg[m]={num_escuelas:0};agg[m].num_escuelas+=n(f.properties.num_escuelas);YEARS.forEach(y=>agg[m][y.field]=(agg[m][y.field]||0)+n(f.properties[y.field]))});alcaldiaData.features.forEach(f=>Object.assign(f.properties,agg[String(f.properties.CVE_MUN||'').padStart(3,'0')]||{num_escuelas:0}))}
function schoolList(cve,mun){return schools.filter(s=>currentTerritory==='ageb'?s.cvegeo===cve:s.mun===mun)}
function conapoSeries(mun){return YEARS.map(y=>{const r=conapo.find(x=>x.mun===mun&&x.anio===y.year);return r?r.pob_00_14:0})}
function corrLabel(r){if(r==null)return['No calculable','corr-low'];const a=Math.abs(r);if(a>=.8)return['Muy fuerte','corr-good'];if(a>=.6)return['Fuerte','corr-good'];if(a>=.4)return['Moderada','corr-mid'];return['Baja','corr-low']}
function miniChart(mat,pop){const W=390,H=135,P=24,all=[...mat,...pop].filter(v=>v>0),min=Math.min(...all),max=Math.max(...all),sx=i=>P+i*(W-2*P)/(YEARS.length-1),sy=v=>H-P-(v-min)/(max-min||1)*(H-2*P);const line=a=>a.map((v,i)=>`${i?'L':'M'}${sx(i).toFixed(1)},${sy(v).toFixed(1)}`).join(' ');return `<svg viewBox="0 0 ${W} ${H}" class="mini-chart" aria-label="Evolución temporal"><path class="chart-mat" d="${line(mat)}"/><path class="chart-pop" d="${line(pop)}"/>${mat.map((v,i)=>`<circle class="chart-dot-mat" cx="${sx(i)}" cy="${sy(v)}" r="2"/>`).join('')}${pop.map((v,i)=>`<circle class="chart-dot-pop" cx="${sx(i)}" cy="${sy(v)}" r="2"/>`).join('')}<text class="chart-label" x="${P}" y="${H-5}">2024</text><text class="chart-label" x="${W-P-24}" y="${H-5}">2035</text></svg><div class="chart-legend"><span><i style="background:#172554"></i>Matrícula</span><span><i style="background:#b45309"></i>CONAPO 0–14</span></div>`}
function popup(f){const p=f.properties,cur=n(p[YEARS[currentIndex].field]),base=n(p.mat_2024_2025),change=pct(cur,base),mun=String(p.CVE_MUN||'').padStart(3,'0'),list=schoolList(p.CVEGEO,mun),title=currentTerritory==='ageb'?`AGEB ${p.CVE_AGEB||''}`:p.NOMGEO;const schoolHtml=list.sort((a,b)=>n(b[YEARS[currentIndex].field])-n(a[YEARS[currentIndex].field])).map(s=>{const sc=pct(n(s[YEARS[currentIndex].field]),n(s.mat_2024_2025));return `<div class="popup-school" style="border-left-color:${pctColor(sc)}"><strong>${s.nombre||'Sin nombre'}</strong>${s.cct||'Sin CCT'} · ${s.nivel||'Sin nivel'}<br>${fmt(s[YEARS[currentIndex].field])} alumnos · ${sc==null?'Sin base':(sc>=0?'+':'')+sc.toFixed(1)+'%'}</div>`}).join('');let compare='';if(currentTerritory==='alcaldia'){const pop=conapoSeries(mun),mat=YEARS.map(y=>n(p[y.field])),a=analysis.find(x=>x.mun===mun),r=a?.correlacion_pearson,[label,cls]=corrLabel(r),cp=pct(pop[currentIndex],pop[0]);compare=`<div class="popup-section"><strong>Comparación demográfica CONAPO</strong><div class="popup-grid"><span>Población 0–14:</span><strong>${fmt(pop[currentIndex])}</strong><span>Variación CONAPO:</span><strong>${cp==null?'—':cp.toFixed(1)+'%'}</strong><span>Correlación temporal:</span><strong class="${cls}">${r==null?'—':Number(r).toFixed(2)} · ${label}</strong></div>${miniChart(mat,pop)}</div>`}return `<div class="popup-wrap"><div class="popup-title">${title}</div><div class="popup-grid"><span>Clave:</span><strong>${p.CVEGEO||mun}</strong><span>Ciclo:</span><strong>${YEARS[currentIndex].label}</strong><span>Matrícula 911 proyectada:</span><strong>${fmt(cur)}</strong><span>Escuelas:</span><strong>${fmt(p.num_escuelas)}</strong><span>Cambio:</span><strong>${change==null?'No calculable':change.toFixed(1)+'%'}</strong><span>Base 2024-2025:</span><strong>${fmt(base)}</strong></div>${compare}<div class="popup-section"><strong>Escuelas en el área (${list.length})</strong><div class="popup-schools">${schoolHtml||'<div class="popup-school">No hay escuelas asociadas.</div>'}</div></div></div>`}
function render(){if(layer)map.removeLayer(layer);const data=currentTerritory==='ageb'?agebData:alcaldiaData,features=data.features.filter(visible),breaks=quantiles(features.map(currentValue));layer=L.geoJSON({type:'FeatureCollection',features},{style:f=>({color:'#475569',weight:currentTerritory==='ageb'?.55:1.4,fillColor:currentVariable==='total'?totalColor(currentValue(f),breaks):pctColor(currentValue(f)),fillOpacity:.78}),onEachFeature:(f,l)=>{l.on({mouseover:e=>e.target.setStyle({weight:2.5,color:'#111827',fillOpacity:.9}),mouseout:e=>layer.resetStyle(e.target)});l.bindPopup(()=>popup(f),{maxWidth:470,maxHeight:560})}}).addTo(map);updateStats(features);updateLegend(breaks);updateCorrelation();updateRanking()}
function updateStats(fs){const total=fs.reduce((s,f)=>s+n(f.properties[YEARS[currentIndex].field]),0),base=fs.reduce((s,f)=>s+n(f.properties.mat_2024_2025),0),sch=fs.reduce((s,f)=>s+n(f.properties.num_escuelas),0),units=currentTerritory==='ageb'?fs.filter(f=>n(f.properties.num_escuelas)>0).length:fs.length;$('totalMatricula').textContent=fmt(total);$('unitsLabel').textContent=currentTerritory==='ageb'?'AGEB con escuelas':'Alcaldías';$('unitsCount').textContent=fmt(units);$('totalEscuelas').textContent=fmt(sch);$('cambioTotal').textContent=base?`${((total-base)/base*100).toFixed(1)}%`:'No calculable'}
function updateLegend(b){let items;if(currentVariable==='percent')items=[['Menor de -10%','#7f0000'],['-10% a -7%','#b2182b'],['-7% a -4%','#d6604d'],['-4% a -2%','#f4a582'],['Estable (-2% a 2%)','#f7f7f7'],['2% a 5%','#d9f0d3'],['5% a 10%','#7fbf7b'],['10% a 20%','#1b7837'],['Mayor de 20%','#00441b'],['Sin base','#d1d5db']];else items=[['Sin matrícula','#e5e7eb'],[`1 – ${Math.round(b[0]).toLocaleString('es-MX')}`,totalColor(1,b)],[`${Math.round(b[0]+1).toLocaleString('es-MX')} – ${Math.round(b[1]).toLocaleString('es-MX')}`,totalColor(b[0]+1,b)],[`${Math.round(b[1]+1).toLocaleString('es-MX')} – ${Math.round(b[2]).toLocaleString('es-MX')}`,totalColor(b[1]+1,b)],[`${Math.round(b[2]+1).toLocaleString('es-MX')} – ${Math.round(b[3]).toLocaleString('es-MX')}`,totalColor(b[2]+1,b)],[`Más de ${Math.round(b[3]).toLocaleString('es-MX')}`,totalColor(b[3]+1,b)]];$('legend').innerHTML=items.map(([t,c])=>`<div class="legend-item"><span class="legend-color" style="background:${c}"></span>${t}</div>`).join('')}
function pearson(x,y){const mx=x.reduce((a,b)=>a+b,0)/x.length,my=y.reduce((a,b)=>a+b,0)/y.length,dx=x.map(v=>v-mx),dy=y.map(v=>v-my),den=Math.sqrt(dx.reduce((s,v)=>s+v*v,0)*dy.reduce((s,v)=>s+v*v,0));return den?dx.reduce((s,v,i)=>s+v*dy[i],0)/den:null}
function updateCorrelation(){if(currentTerritory!=='alcaldia'){$('globalCorrelation').innerHTML='Cambie la vista a <strong>Alcaldías</strong> para consultar CONAPO.';return}const x=[],y=[];alcaldiaData.features.forEach(f=>{const mun=String(f.properties.CVE_MUN).padStart(3,'0'),p=conapoSeries(mun)[currentIndex],m=n(f.properties[YEARS[currentIndex].field]);if(p&&m){x.push(p);y.push(m)}});const r=pearson(x,y),[label,cls]=corrLabel(r);$('globalCorrelation').innerHTML=`Correlación entre alcaldías en ${YEARS[currentIndex].label}: <strong class="${cls}">${r==null?'—':r.toFixed(2)} · ${label}</strong><br><small>Indica qué tan asociadas están la cantidad de población de 0–14 años y la matrícula proyectada entre las 16 alcaldías.</small>`}
function updateRanking(){const sorted=[...analysis].sort((a,b)=>rankMode==='decline'?a.variacion_matricula_pct-b.variacion_matricula_pct:b.variacion_matricula_pct-a.variacion_matricula_pct).slice(0,8);$('ranking').innerHTML=sorted.map((r,i)=>`<div class="rank-row"><strong>${i+1}</strong><span>${r.alcaldia}</span><strong>${r.variacion_matricula_pct>0?'+':''}${r.variacion_matricula_pct.toFixed(1)}%</strong></div>`).join('')}
function downloadReport(){const data=alcaldiaData.features.map(f=>{const p=f.properties,mun=String(p.CVE_MUN).padStart(3,'0'),pop=conapoSeries(mun),mat=n(p[YEARS[currentIndex].field]);return{'Alcaldía':p.NOMGEO,'Ciclo':YEARS[currentIndex].label,'Matrícula proyectada 911':mat,'Población CONAPO 0-14':pop[currentIndex]||0,'Variación matrícula %':(pct(mat,n(p.mat_2024_2025))||0).toFixed(2),'Variación CONAPO %':(pct(pop[currentIndex],pop[0])||0).toFixed(2),'Escuelas':n(p.num_escuelas)}});const h=Object.keys(data[0]),csv='\uFEFF'+[h.join(','),...data.map(r=>h.map(k=>`"${String(r[k]).replaceAll('"','""')}"`).join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`reporte_${YEARS[currentIndex].label}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('yearSlider').oninput=e=>{$('yearSelect').value=e.target.value;currentIndex=+e.target.value;render()};$('yearSelect').onchange=e=>{$('yearSlider').value=e.target.value;currentIndex=+e.target.value;render()};$('territory').onchange=e=>{currentTerritory=e.target.value;$('schoolFilterWrap').style.display=currentTerritory==='ageb'?'block':'none';render()};$('variable').onchange=e=>{currentVariable=e.target.value;render()};$('filterSchools').onchange=e=>{currentFilter=e.target.value;render()};$('panelToggle').onclick=()=>$('panel').classList.toggle('open');$('reportBtn').onclick=downloadReport;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');rankMode=b.dataset.rank;updateRanking()});
Promise.all([fetch('data/ageb_proyecciones.json').then(r=>r.json()),fetch('data/alcaldias.json').then(r=>r.json()),fetch('data/escuelas_proyecciones.json').then(r=>r.json()),fetch('data/conapo_00_14.json').then(r=>r.json()),fetch('data/analisis_alcaldias.json').then(r=>r.json())]).then(([a,b,c,d,e])=>{agebData=a;alcaldiaData=b;schools=c;conapo=d;analysis=e;enrichAlcaldias();render();map.fitBounds(L.geoJSON(agebData).getBounds(),{padding:[10,10]})}).catch(e=>{console.error(e);alert('No se pudieron cargar los datos. Revisa la carpeta data.')});