const YEARS=Array.from({length:12},(_,i)=>{const y=2024+i;return{label:`${y}-${y+1}`,field:`mat_${y}_${y+1}`}});
const map=L.map('map').setView([19.36,-99.13],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);
let agebData,alcaldiaData,schools=[],layer,currentIndex=0,currentTerritory='ageb',currentVariable='total',currentFilter='all';
const $=id=>document.getElementById(id);YEARS.forEach((y,i)=>$('yearSelect').insertAdjacentHTML('beforeend',`<option value="${i}">${y.label}</option>`));
function n(v){return Number(v)||0}function pct(cur,base){return base?((cur-base)/base)*100:null}function currentValue(f){const p=f.properties,cur=n(p[YEARS[currentIndex].field]);return currentVariable==='total'?cur:pct(cur,n(p.mat_2024_2025))}
function visible(f){if(currentTerritory!=='ageb')return true;const k=n(f.properties.num_escuelas);return currentFilter==='with'?k>0:currentFilter==='without'?k===0:true}
function quantiles(vals){const a=vals.filter(v=>v!=null&&v>0).sort((x,y)=>x-y);if(!a.length)return[1,2,3,4];const q=p=>a[Math.floor((a.length-1)*p)];return[q(.2),q(.4),q(.6),q(.8)]}
function totalColor(v,b){if(v<=0)return'#e5e7eb';if(v<=b[0])return'#eff3ff';if(v<=b[1])return'#bdd7e7';if(v<=b[2])return'#6baed6';if(v<=b[3])return'#3182bd';return'#08519c'}
function pctColor(v){if(v==null)return'#e5e7eb';if(v<-20)return'#8b0000';if(v<-10)return'#d73027';if(v<-2)return'#fc8d59';if(v<=2)return'#f1f1f1';if(v<=10)return'#a6dba0';if(v<=20)return'#5aae61';return'#1b7837'}
function enrichAlcaldias(){const agg={};agebData.features.forEach(f=>{const m=String(f.properties.CVE_MUN||'').padStart(3,'0');if(!agg[m])agg[m]={num_escuelas:0};agg[m].num_escuelas+=n(f.properties.num_escuelas);YEARS.forEach(y=>agg[m][y.field]=(agg[m][y.field]||0)+n(f.properties[y.field]))});alcaldiaData.features.forEach(f=>Object.assign(f.properties,agg[String(f.properties.CVE_MUN||'').padStart(3,'0')]||{num_escuelas:0}))}
function schoolList(cve,mun){return schools.filter(s=>currentTerritory==='ageb'?s.cvegeo===cve:String(s.cvegeo||'').slice(2,5)===mun)}
function popup(f){const p=f.properties,cur=n(p[YEARS[currentIndex].field]),base=n(p.mat_2024_2025),change=pct(cur,base),mun=String(p.CVE_MUN||'').padStart(3,'0'),list=schoolList(p.CVEGEO,mun);const title=currentTerritory==='ageb'?`AGEB ${p.CVE_AGEB||''}`:p.NOMGEO;const shown=list.slice(0,30).map(s=>`<div class="popup-school"><strong>${s.nombre||'Sin nombre'}</strong>${s.cct||'Sin CCT'} · ${s.nivel||'Sin nivel'} · ${n(s[YEARS[currentIndex].field]).toLocaleString('es-MX')} alumnos</div>`).join('');return`<div class="popup-title">${title}</div><div class="popup-grid"><span>Clave:</span><strong>${p.CVEGEO||mun}</strong><span>Ciclo:</span><strong>${YEARS[currentIndex].label}</strong><span>Matrícula:</span><strong>${cur.toLocaleString('es-MX')}</strong><span>Escuelas:</span><strong>${n(p.num_escuelas).toLocaleString('es-MX')}</strong><span>Cambio:</span><strong>${change==null?'No calculable':change.toFixed(1)+'%'}</strong><span>Base 2024-2025:</span><strong>${base.toLocaleString('es-MX')}</strong><span>Final 2035-2036:</span><strong>${n(p.mat_2035_2036).toLocaleString('es-MX')}</strong></div><div class="popup-schools"><strong>Escuelas en el área (${list.length})</strong>${shown}${list.length>30?`<div class="popup-note">Se muestran 30 de ${list.length} escuelas.</div>`:''}</div>`}
function render(){if(layer)map.removeLayer(layer);const data=currentTerritory==='ageb'?agebData:alcaldiaData,features=data.features.filter(visible),breaks=quantiles(features.map(currentValue));layer=L.geoJSON({type:'FeatureCollection',features},{style:f=>({color:'#475569',weight:currentTerritory==='ageb'?.55:1.4,fillColor:currentVariable==='total'?totalColor(currentValue(f),breaks):pctColor(currentValue(f)),fillOpacity:.76}),onEachFeature:(f,l)=>{l.on({mouseover:e=>e.target.setStyle({weight:2.5,color:'#111827',fillOpacity:.9}),mouseout:e=>layer.resetStyle(e.target)});l.bindPopup(()=>popup(f),{maxWidth:420})}}).addTo(map);updateStats(features);updateLegend(breaks)}
function updateStats(fs){const total=fs.reduce((s,f)=>s+n(f.properties[YEARS[currentIndex].field]),0),base=fs.reduce((s,f)=>s+n(f.properties.mat_2024_2025),0),sch=fs.reduce((s,f)=>s+n(f.properties.num_escuelas),0),units=currentTerritory==='ageb'?fs.filter(f=>n(f.properties.num_escuelas)>0).length:fs.length;$('totalMatricula').textContent=total.toLocaleString('es-MX');$('unitsLabel').textContent=currentTerritory==='ageb'?'AGEB con escuelas':'Alcaldías';$('unitsCount').textContent=units.toLocaleString('es-MX');$('totalEscuelas').textContent=sch.toLocaleString('es-MX');$('cambioTotal').textContent=base?`${((total-base)/base*100).toFixed(1)}%`:'No calculable'}
function updateLegend(b){let items;if(currentVariable==='percent')items=[['Menor de -20%','#8b0000'],['-20% a -10%','#d73027'],['-10% a -2%','#fc8d59'],['Estable (-2% a 2%)','#f1f1f1'],['2% a 10%','#a6dba0'],['10% a 20%','#5aae61'],['Mayor de 20%','#1b7837'],['Sin base','#e5e7eb']];else items=[['Sin matrícula','#e5e7eb'],[`1 – ${Math.round(b[0]).toLocaleString('es-MX')}`,totalColor(1,b)],[`${Math.round(b[0]+1).toLocaleString('es-MX')} – ${Math.round(b[1]).toLocaleString('es-MX')}`,totalColor(b[0]+1,b)],[`${Math.round(b[1]+1).toLocaleString('es-MX')} – ${Math.round(b[2]).toLocaleString('es-MX')}`,totalColor(b[1]+1,b)],[`${Math.round(b[2]+1).toLocaleString('es-MX')} – ${Math.round(b[3]).toLocaleString('es-MX')}`,totalColor(b[2]+1,b)],[`Más de ${Math.round(b[3]).toLocaleString('es-MX')}`,totalColor(b[3]+1,b)]];$('legend').innerHTML=items.map(([t,c])=>`<div class="legend-item"><span class="legend-color" style="background:${c}"></span>${t}</div>`).join('')}
$('yearSlider').oninput=e=>{$('yearSelect').value=e.target.value;currentIndex=+e.target.value;render()};$('yearSelect').onchange=e=>{$('yearSlider').value=e.target.value;currentIndex=+e.target.value;render()};$('territory').onchange=e=>{currentTerritory=e.target.value;$('schoolFilterWrap').style.display=currentTerritory==='ageb'?'block':'none';render()};$('variable').onchange=e=>{currentVariable=e.target.value;render()};$('filterSchools').onchange=e=>{currentFilter=e.target.value;render()};$('panelToggle').onclick=()=>$('panel').classList.toggle('open');
Promise.all([fetch('data/ageb_proyecciones.json').then(r=>r.json()),fetch('data/alcaldias.json').then(r=>r.json()),fetch('data/escuelas_proyecciones.json').then(r=>r.json())]).then(([a,b,c])=>{agebData=a;alcaldiaData=b;schools=c;enrichAlcaldias();render();map.fitBounds(L.geoJSON(agebData).getBounds(),{padding:[10,10]})}).catch(e=>{console.error(e);alert('No se pudieron cargar los datos del visor. Revisa la carpeta data.')});